# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Triggered from mainnet
  repository_dispatch:
    types: [triggered_from_mainnet]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  attestations: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'test' branch of Main Repository
        uses: actions/checkout@v4
        with:
          repository: SwapMarket/usdt
          ref: test

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update vite.config.mjs
        run: |
          sed -i 's|base: "/usdt/",*$|base: "/usdt-testnet/",|g' vite.config.mjs

      - name: Copy config
        run: npm run testnet

      - name: Install Go
        run: wget https://go.dev/dl/go1.21.3.linux-amd64.tar.gz && sudo tar -C /usr/local -xzf go1.21.3.linux-amd64.tar.gz
        
      - name: Build
        env:
          PRIV_KEY: ${{ secrets.PRIV_KEY }}
          PUB_KEY: ${{ secrets.PUB_KEY }}
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
